### ISSUE TITLE
Document how to obtain public root key of a wallet to generate receiving addresses for a shop

### ISSUE THREAD

**Issue by jbax** [uniVocity/shopify#6]
A wallet provides multiple receiving addresses. Would be great to be able to have a step by step guide for store owners on how to copy-and-paste part of list of possible receiving addresses. If that is not possible I'll build a desktop tool to generate the shop wallet, give the seed phrase to the shop owner so it can be restored in his preferred wallet, then upload the public root key to their shopify store.

Each receiving address could be bound to a different order in shopify to make identification of orders fast and easy. Consumer A pays to receiving address 1, consumer B pays to receiving address 2, etc. 

It doesn't look like we can inject any sort of metadata in the blockchain so the consumer wallet can tell "payment for order number 12345" and I'm trying to be as less hacky as possible to properly assign payments from `n` wallets to a destination address.

**Comment by jbax** [comment]
Adding further details:

The app won't have private keys of anyone ever and will be unable to produce receiving addresses unless we could create them on the fly based on a public key (which I don't think it's possible). The second we start managing private keys is the moment when we open up to a huge can of works in regards to financial liability, exposure to hacks, and all sorts of shenanigans we should not have to deal with.

Unless there's a clean and SAFE solution, shops will have to submit a list of receiving addresses to be used for assigning orders to customer payments, and the app will have to ensure there's never a receiving address that is being used twice at the same time.

 @SebastienGllmt do you have any suggestion?

**Comment by katomm** [comment]
Hello,
Thank you for doing this. There is no need to collect addresses in such a list. The public root key is sufficient to generate new public addresses. Yoroi does the same.

**Comment by jbax** [comment]
Very cool and thanks so much for helping out! So we need to document the
sequence of steps needed to get the public root key from existing wallets
(daedalus, yoroi, adalite, etc)

**Comment by jbax** [comment]
Will happen in this other project I'm working on: https://github.com/uniVocity/free-commerce

That's going to be specially built desktop wallet for e-commerce that can be run offline and generate a seed using the steps described in issue #9, upload the public root key automatically, display each purchase associated with a transaction, and run without a private key (basically in read-only-mode).
