### ISSUE TITLE
Query balance of a wallet (javascript)

### ISSUE THREAD

**Issue by jbax** [uniVocity/shopify#8]
I'm still not sure how to cleanly handle the situation where a payment for a large order is made from multiple addresses, and how to track reconcile everything to fulfill an order.

My first approach would be to at the end of the checkout process:

1 - display total payable with wallet address
2 - ask customer provide one or more wallets where funds will come from to pay the order

In this case the checkout page would display the available balance in each one of the customer address and the system will link it all together then wait for the money to be transferred from these specific wallets, so we can know person A paid X amount for an item.

--- Now, this can get problematic. People can make a mistake and overpay, or still pay partially. 

Maybe @SebastienGllmt has a better approach to handle this sort of situation, and make it easier for us to to link one or more specific payments to a given address, and identify what wallet was used to pay for a given item, and ensure that the payment was fulfilled so that an item can be sent.

**Comment by NinjaNoel** [comment]
apologies if this is a silly question, but why do you need to know the sending address? what if i send my payment from an exchange like coinbase? I would have expected each address to be unique for each payment, so as long as all the money arrives, source should not be required

**Comment by jbax** [comment]
There are no silly questions.

The problem I'm thinking I'll have is this:

SCENARIO 1

- you buy a t-shirt for 100 ADA.

Shop displays you (Person A) the wallet address to pay.
Shop displays Person B the same wallet address to pay for a shoe that also costs 100 ADA.

Shop address is the same for both Person A and B. Person A sends 100 ADA from an address the shop doesn't know. 

Given that shop only sees 100 ADA come from nowhere into its wallet, how can I determine who paid? Was it Person A or Person B? It complicates further if one of the buyers pay 75 ADA from one wallet and the remaining 25 from another.

The only clean solution for this that I can see is to provide a different payment address to each customer. That's easily doable but at one point (if I can't get infinite addresses) I'll have to rotate them and on a black friday sale I may not allow one transaction to be made with ADA.

**Comment by jbax** [comment]
Ok so never a receiving address will be used twice at the same time (exchange addresses and other issues)

But the issue remains: the app won't have private keys of anyone ever and will be unable to produce receiving addresses (unless we could create one based on a public key, which I don't think it's possible). 

Unless there's a clean and SAFE solution, shops will have to submit a list of receiving addresses to be used for assigning orders to customer payments.

**Comment by jbax** [comment]
Closing this to open a new issue to deal specifically about the receiving addresses. No need to query balances of anything.
