### ISSUE TITLE
Generate payment addresses from a public root key

### ISSUE THREAD

**Issue by jbax** [uniVocity/shopify#9]
So shops will have to provide their **public root key** to the app (how, I'm not sure, issue #6 aims to address that part). From there, whenever a new order is created from that shop, its key will be used to generate a unique payment address that will be associated with that particular order.

What we need now is a method that given the public root key, produces a receiving address.

If anyone can help out that would be great. Just submit a PR with a simple java class with a main method that I can execute by itself, and then I'll refactor it to make it work with the rest of the code.

I have the impression we'll need to use something like `cardano-cli ` which must be available to the server, and then invoke it with a `ProcessBuilder` or even `Runtime.exec` to call a shell script. 

If that's the case the only thing I'll need is the sequence of commands to invoke the `cardano-cli` (if this is the right tool to use), provide the public root key to that and get a new payment address from it - if it can dump 1000 addresses to a text file I can load when needed that would be pretty perfect.

**Comment by SebastienGllmt** [comment]
You may be interested in using https://github.com/Emurgo/cardano-serialization-lib 

Our React-Native mobile bindings contain Java bindings that might be useful to you https://github.com/Emurgo/react-native-haskell-shelley or you can use our Rust library as a reference implementation and re-implement the logic in Java

**Comment by jbax** [comment]
Thank you Sebastien!

I scanned through the methods in [HaskellShelleyModule](https://github.com/Emurgo/react-native-haskell-shelley/blob/master/android/src/main/java/io/emurgo/rnhaskellshelley/HaskellShelleyModule.java) but just from looking at the code it's not clear to me what to use for generating a new payment address from a public root key. 

I could not make sense of any method name there that kind of matches what I'm trying to do. I'm sure there are many names for the same thing. 

If you were to use the code in these repositories you pointed out, how would you go about implement that? I'm just looking at the specific steps to take, e.g. "call this method `generateReceivingAddress(publicRootKey)`" (if something like that exists), or which relevant functions are there that will allow me to build a `generateReceivingAddress(publicRootKey)` function.

**Comment by SebastienGllmt** [comment]
Depends what kind of address you want. For example, if the store wants to have enterprise addresses (addresses that can't stake), it would look something like this.

```
// You can also use from_bip39_entropy if you want a create it from a recovery phrase instead
const rootPk = Wasm.Bip32PrivateKey.from_bytes( /* private key here. */);

// this is assuming the store wants its wallet to be compatible with Yoroi / Daedalus / etc

// generate an address pk
const addressPk = rootPk
    .derive(1852 + 0x80000000) // Cardano uses 1852 for Shelley purpose paths
    .derive(1815 + 0x80000000) // Cardano coin type
    .derive(0 + 0x80000000) // account #0
    .derive(0) // external chain (see bip44)
    .derive(0); // 0th account

// get the address public key hash
const keyHash = addressPk 
    .to_raw_key() // strips the chain code
    .to_public()
    .hash();

// generate the address
const enterpriseAddr = Wasm.EnterpriseAddress.new(
    1, // mainnet network id
    Wasm.StakeCredential.from_keyhash(keyHash)
);

// get bech32 for address
const bech32 = enterpriseAddr.to_address().to_bech32();

console.log(bech32);
```

result will be something like `addr1v9gzxuq2z849rp76tchd4ccvxjm0ayr8l9fwd6v3k79zt9gjtu5sq`

I'm not sure if we have enterprise address yet for mobile, but the other Shelley address types are generated in a similar way.

**Comment by jbax** [comment]
Thanks but the example you gave seems to be using a private key. Also our
use case here is (hopefully) simpler than what you think as we don't care
about enterprise addresses nor staking.

So let me start over to make sure there is no misunderstanding:

 1. the shopify app doesn't have anyone's private key (from neither the
shop who installs the app nor the customers).

 2. If possible no private key will ever have to be created by online store
for the purpose of using the app and selling goods in ADA. We assume the
shop owner has his wallet in daedalus for example, and the customer too.

  2.1. At no point the app server should have access to anyone's funds,
even if temporarily.

 3. To enable ada payments, the shop will provide its *public* root key.
Not private. (I got this info from issue #6, please let me know if it's not
possible)

  3.1. That root key will be used to generate new receiving addresses on
demand (this is the issue we are discussing).

  3.2. Every receiving address must be unique and the format is irrelevant.
For simplicity let's assume we generate shelley receiving addresses like
what daedalus gives out.

  3.3. When someone sends ADA to that address, the store owner will receive
the ADA directly in their wallet, to which we have no access (we don't know
and don't want to know the private key)

 4. When a customer of a store makes a purchase, a new receiving address
will be generated and associated with the order

 5. Once the total amount of the order is paid to the receiving address,
the order is fulfilled and the shop can send the items purchased to the
customer.

  5.1. we need to be able to determine that X amount was sent to that
particular receiving address, instead of mixing funds with the whole
balance of the wallet managed by the store.

Again the shopify app is a mere observer of transactions made from one or
more (customer) addresses to another (associated with an online purchase -
funds go straight to the shop owner wallet).

It doesn't handle private keys - unless there's no other way, in such a
case we'll have to create one temporary wallet per customer order, which
not only is less safe, but also adds one extra transaction fee to the
process as funds will be moved from the temporary wallet to the shop owner
wallet.

**Comment by SebastienGllmt** [comment]
Using a public key is the exact same code example but with one step removed. Just start with `Bip32PublicKey` and remove the `to_public` line.

**Comment by jbax** [comment]
Thanks man you are the best

**Comment by jbax** [comment]
I was able to get this working as expected using the [cardano-address](https://github.com/input-output-hk/cardano-addresses) utility which is part of [adrestia](https://github.com/input-output-hk/adrestia). I'll just leave the correct sequence of commands here in case anyone else needs it:


Generete a mnemonic (or use one if you have it)

```
cardano-address recovery-phrase generate --size 24 > mnemonic.prv
```

Convert the mnemonic to a private key:

```
cat mnemonic.prv | cardano-address key from-recovery-phrase Shelley > root.prv
```

Generate the public root key:
```
cat root.prv | cardano-address key child 1852H/1815H/0H | cardano-address key public > THIS.publicKey
```

I'm creating a desktop app for store owners, to automate this: https://github.com/uniVocity/free-commerce

Once the public key is uploaded to the server, I can use this to generate payment addresses:

```
cat THIS.publicKey | cardano-address key child 0/0 | cardano-address address payment --network-tag 1 > payment.address.0
cat THIS.publicKey | cardano-address key child 0/1 | cardano-address address payment --network-tag 1 > payment.address.1
...
cat THIS.publicKey | cardano-address key child 0/10 | cardano-address address payment --network-tag 1 > payment.address.10
```

Note that wallets such as Deadalus allow only 20 unused addresses. If you create an address using `child 0/100` any payment made to the address that's generated will not show up.

This is a limitation on the BIP-44 protocol (see [here](https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postWallet)) so store owners will have the option to submit more public keys for other wallets to allow multiple concurrent pending payments, or to simply ignore this limitation - I'll have to create e desktop wallet based on `cardano-wallet` to display transactions made to addresses that do not respect that gap.

**Comment by jbax** [comment]
Update: using `child 1/1`, `child 2/1` , `child 3/1` and so on will create accounts which will later appear on daedalus (not supported yet but it's planned). This is compatible with the BIP44 spec and allows creating many addresses at the same time. Up to 2^31 accounts can be generated. That should be enough
